services:
  backend:
    container_name: "app-api_${NODE_ENV}"
    build: "./backend"
    env_file:
      - ".env"
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    develop:
      watch:
        - action: sync
          path: "./backend"
          target: "/app"
          ignore:
            - "node_modules/"
            - "pnpm-lock.yaml"
            - "Dockerfile"
            - ".dockerignore"
        - action: rebuild
          path: "package.json"

  frontend:
    container_name: "app_${NODE_ENV}"
    depends_on:
      - backend
    build: 
      context: "./frontend"
      dockerfile: "Dockerfile.${NODE_ENV}"
    env_file:
      - ".env"
    ports:
      - "${VITE_PORT}:80"
      - "${VITE_DEV_PORT}:5173"
    develop:
      watch:
        - action: sync
          path: "./frontend"
          target: "/app"
          ignore:
            - "node_modules/"
            - "pnpm-lock.yaml"
            - "Dockerfile.dev"
            - "Dockerfile.prod"
            - ".dockerignore"
        - action: rebuild
          path: "package.json"
